//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Dnn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnnProfile
    {
        public int UserID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
        public int Visibility { get; set; }
    }
}
