//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_RMA
    {
        public hcc_RMA()
        {
            this.hcc_RMAItem = new HashSet<hcc_RMAItem>();
        }
    
        public System.Guid bvin { get; set; }
        public System.Guid OrderBvin { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Comments { get; set; }
        public int Status { get; set; }
        public System.DateTime DateOfReturn { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long StoreId { get; set; }
    
        public virtual ICollection<hcc_RMAItem> hcc_RMAItem { get; set; }
        public virtual hcc_Order hcc_Order { get; set; }
    }
}
