//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_RewardsPoints
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public int Points { get; set; }
        public int PointsHeld { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public long StoreId { get; set; }
    }
}
