//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Country
    {
        public hcc_Country()
        {
            this.hcc_CountryTranslations = new HashSet<hcc_CountryTranslation>();
            this.hcc_Regions = new HashSet<hcc_Region>();
        }
    
        public System.Guid CountryId { get; set; }
        public string CultureCode { get; set; }
        public string SystemName { get; set; }
        public string IsoCode { get; set; }
        public string IsoAlpha3 { get; set; }
        public string IsoNumeric { get; set; }
        public string PostalCodeValidationRegex { get; set; }
    
        public virtual ICollection<hcc_CountryTranslation> hcc_CountryTranslations { get; set; }
        public virtual ICollection<hcc_Region> hcc_Regions { get; set; }
    }
}
