//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_TaxSchedules
    {
        public hcc_TaxSchedules()
        {
            this.hcc_Taxes = new HashSet<hcc_Taxes>();
        }
    
        public long Id { get; set; }
        public long StoreId { get; set; }
        public string Name { get; set; }
        public decimal DefaultRate { get; set; }
        public decimal DefaultShippingRate { get; set; }
    
        public virtual hcc_Stores hcc_Stores { get; set; }
        public virtual ICollection<hcc_Taxes> hcc_Taxes { get; set; }
    }
}
