//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_AnalyticsEvent
    {
        public long AnalyticsEventId { get; set; }
        public string UserId { get; set; }
        public long StoreId { get; set; }
        public string Action { get; set; }
        public Nullable<System.Guid> ObjectId { get; set; }
        public string AdditionalData { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.Guid> SessionGuid { get; set; }
        public Nullable<System.Guid> ShoppingSessionGuid { get; set; }
    }
}
