//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_StoresXUsers
    {
        public long Id { get; set; }
        public long StoreId { get; set; }
        public long UserId { get; set; }
        public int AccessMode { get; set; }
    
        public virtual hcc_Stores hcc_Stores { get; set; }
        public virtual hcc_UserAccounts hcc_UserAccounts { get; set; }
    }
}
