//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Region
    {
        public hcc_Region()
        {
            this.hcc_RegionTranslations = new HashSet<hcc_RegionTranslation>();
        }
    
        public System.Guid RegionId { get; set; }
        public System.Guid CountryId { get; set; }
        public string Abbreviation { get; set; }
        public string SystemName { get; set; }
    
        public virtual ICollection<hcc_RegionTranslation> hcc_RegionTranslations { get; set; }
        public virtual hcc_Country hcc_Countries { get; set; }
    }
}
