//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_HtmlTemplateTranslation
    {
        public long HtmlTemplateTranslationId { get; set; }
        public long HtmlTemplateId { get; set; }
        public string Culture { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string RepeatingSection { get; set; }
    
        public virtual hcc_HtmlTemplates hcc_HtmlTemplates { get; set; }
    }
}
