//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_GiftCard
    {
        public long GiftCardId { get; set; }
        public long StoreId { get; set; }
        public Nullable<long> LineItemId { get; set; }
        public string CardNumber { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime IssueDateUtc { get; set; }
        public System.DateTime ExpirationDateUtc { get; set; }
        public string RecipientEmail { get; set; }
        public string RecipientName { get; set; }
        public decimal UsedAmount { get; set; }
        public bool Enabled { get; set; }
    }
}
