//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ProductOptions
    {
        public hcc_ProductOptions()
        {
            this.hcc_ProductOptionsItems = new HashSet<hcc_ProductOptionsItems>();
            this.hcc_ProductOptionTranslations = new HashSet<hcc_ProductOptionTranslation>();
            this.hcc_ProductXOption = new HashSet<hcc_ProductXOption>();
        }
    
        public System.Guid bvin { get; set; }
        public long StoreId { get; set; }
        public int OptionType { get; set; }
        public bool NameIsHidden { get; set; }
        public bool IsVariant { get; set; }
        public bool IsShared { get; set; }
        public string Settings { get; set; }
        public bool IsColorSwatch { get; set; }
    
        public virtual ICollection<hcc_ProductOptionsItems> hcc_ProductOptionsItems { get; set; }
        public virtual ICollection<hcc_ProductOptionTranslation> hcc_ProductOptionTranslations { get; set; }
        public virtual ICollection<hcc_ProductXOption> hcc_ProductXOption { get; set; }
    }
}
