//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Audit
    {
        public long Id { get; set; }
        public System.DateTime TimeStampUtc { get; set; }
        public int SourceModule { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public string UserIdText { get; set; }
        public int Severity { get; set; }
        public long StoreId { get; set; }
    }
}
