//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_CustomUrl
    {
        public string bvin { get; set; }
        public string RequestedUrl { get; set; }
        public string RedirectToUrl { get; set; }
        public bool IsPermanentRedirect { get; set; }
        public int SystemDataType { get; set; }
        public string SystemData { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long StoreId { get; set; }
    }
}
