//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ProductFile
    {
        public hcc_ProductFile()
        {
            this.hcc_ProductFileXProduct = new HashSet<hcc_ProductFileXProduct>();
        }
    
        public System.Guid bvin { get; set; }
        public string FileName { get; set; }
        public string ShortDescription { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long StoreId { get; set; }
    
        public virtual ICollection<hcc_ProductFileXProduct> hcc_ProductFileXProduct { get; set; }
    }
}
