//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_CatalogRoles
    {
        public long CatalogRoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> ProductTypeId { get; set; }
        public long StoreId { get; set; }
    
        public virtual hcc_Category hcc_Category { get; set; }
        public virtual hcc_Product hcc_Product { get; set; }
        public virtual hcc_ProductType hcc_ProductType { get; set; }
    }
}
