//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_Product
    {
        public hcc_Product()
        {
            this.hcc_ProductInventory = new HashSet<hcc_ProductInventory>();
            this.hcc_ProductXCategory = new HashSet<hcc_ProductXCategory>();
            this.hcc_ProductPropertyValue = new HashSet<hcc_ProductPropertyValue>();
            this.hcc_BundledProducts = new HashSet<hcc_BundledProducts>();
            this.hcc_ProductTranslations = new HashSet<hcc_ProductTranslation>();
            this.hcc_CatalogRoles = new HashSet<hcc_CatalogRoles>();
            this.hcc_ProductImage = new HashSet<hcc_ProductImage>();
            this.hcc_ProductReview = new HashSet<hcc_ProductReview>();
            this.hcc_ProductVolumeDiscounts = new HashSet<hcc_ProductVolumeDiscounts>();
            this.hcc_Variants = new HashSet<hcc_Variants>();
            this.hcc_WishListItems = new HashSet<hcc_WishListItem>();
            this.hcc_ProductFileXProduct = new HashSet<hcc_ProductFileXProduct>();
            this.hcc_ProductRelationships = new HashSet<hcc_ProductRelationship>();
            this.hcc_ProductXOption = new HashSet<hcc_ProductXOption>();
        }
    
        public long Id { get; set; }
        public System.Guid bvin { get; set; }
        public string SKU { get; set; }
        public Nullable<System.Guid> ProductTypeId { get; set; }
        public decimal ListPrice { get; set; }
        public decimal SitePrice { get; set; }
        public decimal SiteCost { get; set; }
        public int TaxExempt { get; set; }
        public string TaxClass { get; set; }
        public int NonShipping { get; set; }
        public int ShipSeparately { get; set; }
        public int ShippingMode { get; set; }
        public decimal ShippingWeight { get; set; }
        public decimal ShippingLength { get; set; }
        public decimal ShippingWidth { get; set; }
        public decimal ShippingHeight { get; set; }
        public int Status { get; set; }
        public string ImageFileSmall { get; set; }
        public string ImageFileMedium { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int MinimumQty { get; set; }
        public Nullable<System.Guid> ManufacturerID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public int GiftWrapAllowed { get; set; }
        public decimal ExtraShipFee { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string TemplateName { get; set; }
        public string PreContentColumnId { get; set; }
        public string PostContentColumnId { get; set; }
        public string RewriteUrl { get; set; }
        public string CustomProperties { get; set; }
        public decimal GiftWrapPrice { get; set; }
        public long StoreId { get; set; }
        public bool Featured { get; set; }
        public Nullable<bool> AllowReviews { get; set; }
        public int OutOfStockMode { get; set; }
        public bool IsAvailableForSale { get; set; }
        public bool IsUserPrice { get; set; }
        public bool HideQty { get; set; }
        public bool IsSearchable { get; set; }
        public bool IsBundle { get; set; }
        public bool IsGiftCard { get; set; }
        public bool IsRecurring { get; set; }
        public Nullable<int> RecurringInterval { get; set; }
        public Nullable<int> RecurringIntervalType { get; set; }
        public int ShippingCharge { get; set; }
    
        public virtual ICollection<hcc_ProductInventory> hcc_ProductInventory { get; set; }
        public virtual ICollection<hcc_ProductXCategory> hcc_ProductXCategory { get; set; }
        public virtual ICollection<hcc_ProductPropertyValue> hcc_ProductPropertyValue { get; set; }
        public virtual hcc_Manufacturer hcc_Manufacturer { get; set; }
        public virtual hcc_ProductType hcc_ProductType { get; set; }
        public virtual hcc_Vendor hcc_Vendor { get; set; }
        public virtual ICollection<hcc_BundledProducts> hcc_BundledProducts { get; set; }
        public virtual ICollection<hcc_ProductTranslation> hcc_ProductTranslations { get; set; }
        public virtual ICollection<hcc_CatalogRoles> hcc_CatalogRoles { get; set; }
        public virtual ICollection<hcc_ProductImage> hcc_ProductImage { get; set; }
        public virtual ICollection<hcc_ProductReview> hcc_ProductReview { get; set; }
        public virtual ICollection<hcc_ProductVolumeDiscounts> hcc_ProductVolumeDiscounts { get; set; }
        public virtual ICollection<hcc_Variants> hcc_Variants { get; set; }
        public virtual ICollection<hcc_WishListItem> hcc_WishListItems { get; set; }
        public virtual ICollection<hcc_ProductFileXProduct> hcc_ProductFileXProduct { get; set; }
        public virtual ICollection<hcc_ProductRelationship> hcc_ProductRelationships { get; set; }
        public virtual ICollection<hcc_ProductXOption> hcc_ProductXOption { get; set; }
    }
}
