//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ShippingMethod
    {
        public hcc_ShippingMethod()
        {
            this.hcc_ShippingMethodTranslations = new HashSet<hcc_ShippingMethodTranslation>();
        }
    
        public System.Guid bvin { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public decimal Adjustment { get; set; }
        public int AdjustmentType { get; set; }
        public string ShippingProviderId { get; set; }
        public long StoreId { get; set; }
        public long ZoneId { get; set; }
        public string Settings { get; set; }
        public int VisibilityMode { get; set; }
        public Nullable<decimal> VisibilityAmount { get; set; }
        public int VisibilityModeSecondary { get; set; }
        public Nullable<decimal> VisibilityAmountSecondary { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<hcc_ShippingMethodTranslation> hcc_ShippingMethodTranslations { get; set; }
    }
}
