//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotcakes.Commerce.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hcc_ShippingMethodTranslation
    {
        public long ShippingMethodTranslationId { get; set; }
        public System.Guid ShippingMethodId { get; set; }
        public string Culture { get; set; }
        public string Name { get; set; }
    
        public virtual hcc_ShippingMethod hcc_ShippingMethod { get; set; }
    }
}
